proxy:
    image: nginx
    links:
        - frontend
        - backend
    volumes:
        - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "3333:80"
frontend:
    image: nginx
    volumes:
        - ./frontend:/usr/share/nginx/html
backend:
    image: tomcat
    links: 
        - database
    volumes:
        - ./backend/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
database:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=kanban
        - MYSQL_USER=kanban
        - MYSQL_PASSWORD=k4nb4n
