proxy:
    image: nginx
    links:
        - frontend
        - backend
    volumes:
        - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "3333:80"
frontend:
    image: nginx
    volumes:
        - ./frontend:/usr/share/nginx/html
backend:
    image: tomcat
    links: 
        - database
    volumes:
        - ./java_backend/managercontext.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
        - ./java_backend/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
        - ./java_backend/mysql-connector-java-5.1.40-bin.jar:/usr/local/tomcat/lib/mysql-connector-java-5.1.40-bin.jar
        - ./java_backend/logs:/usr/local/tomcat/logs
        - /usr/local/tomcat/webapps
database:
    image: mysql
    volumes:
        - ./sbin:/kanbanscripts
        - ./sbin/config.sh:/root/.yukan_config.sh
    environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=kanban
        - MYSQL_USER=kanban
        - MYSQL_PASSWORD=k4nb4n
